services:
  - type: web
    name: telegram-bot
    env: python
    plan: free
    buildCommand: "pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt"
    startCommand: "bash start.sh"
